// react/players_CRUD2/src/App.jsx
/** @format
 * Copy paste your code from the App.jsx file here from the previous exercise.
 *
 * Use similar logic as in the Vue CRUD2 exercise and add authentication to the app.
 * 
 * Backend is still using Basic Auth, so you must use the same logic as in the Vue exercise. 
 * 
 * REMEMBER: use the same ids, classes and attributes as in the Vue exercise in the same places to pass the tests. Remember to pass in the appropriate props to the child components. 

 * BEWARE: The component props may be different from the Vue exercise and the tests will not pass if you use the wrong props.
 */

import { useState, useEffect } from "react";
const url = "http://localhost:3001/api/players/";
import { REQ_STATUS } from "../cypress/e2e/constants.js";

import { AuthUser } from "./components/AuthUser.jsx";
import { AddPlayer } from "./components/AddPlayer";
import { ListPlayers } from "./components/ListPlayers.jsx";
import { SelectedPlayer } from "./components/SelectedPlayer.jsx";
import { RequestStatus } from "./components/RequestStatus.jsx";

function App() {
  const [players, setPlayers] = useState([]);
  const [selectedPlayer, setSelectedPlayer] = useState(null);
  const [requestStatus, setRequestStatus] = useState(REQ_STATUS.loading);
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  useEffect(() => {
    fetchAllPlayers();
  }, [isLoggedIn]);

  const registerUser = async (newUsername, newPassword) => {
    try {
      setUsername(newUsername)
      setPassword(newPassword)
      setRequestStatus(REQ_STATUS.loading);
      const response = await fetch("http://localhost:3001/api/users", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({username: newUsername, password: newPassword}),
      });
  
      if (response.ok) {
        setIsLoggedIn(true);
        setRequestStatus(REQ_STATUS.success);
      } else {
        setRequestStatus(REQ_STATUS.error);
        setUsername("")
        setPassword("")
        console.error("Failed to register user:", response.statusText);
      }
    } catch (error) {
      setRequestStatus(REQ_STATUS.error);
      setUsername("")
      setPassword("")
      console.error(error);
    }
  };

  const loginUser = async (loginUsername, loginPassword) => {
    try {
      setUsername(loginUsername);
      setPassword(loginPassword);
      setRequestStatus(REQ_STATUS.loading);
      setIsLoggedIn(true);
      setRequestStatus(REQ_STATUS.success);
    } catch (error) {
      setRequestStatus(REQ_STATUS.error);
      setUsername("")
      setPassword("")
      console.error(error);
    }
  };
  
  const logoutUser = async () => {
    setRequestStatus(REQ_STATUS.loading);
    setPlayers([])
    setSelectedPlayer(null);
    setIsLoggedIn(false);
    setUsername("")
    setPassword("")
    setRequestStatus("");
  };

  const fetchData = async (url) => {
    const res = await fetch(url, {
      method: "GET",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json;charset=UTF-8",
        Authorization: `Basic ${window.btoa(`${username}:${password}`)}`,
      },
    });

    const data = await res.json();
    return data;
  };

  const fetchAllPlayers = async () => {
    try {
      setRequestStatus(REQ_STATUS.loading);
      const players = await fetchData("http://localhost:3001/api/players");
      setPlayers(players);
      setRequestStatus(REQ_STATUS.success);
    } catch (error) {
      console.error(error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  const fetchPlayerById = async (playerId) => {
    try {
      setRequestStatus(REQ_STATUS.loading);
      const player = await fetchData(
        `http://localhost:3001/api/players/${playerId}`
      );
      setSelectedPlayer(player);
      setRequestStatus(REQ_STATUS.success);
    } catch (error) {
      console.error(error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  const addPlayer = async (newPlayerName) => {
    try {
      setRequestStatus(REQ_STATUS.loading);

      const response = await fetch("http://localhost:3001/api/players", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Basic ${window.btoa(`${username}:${password}`)}`,
        },
        body: JSON.stringify({ name: newPlayerName }),
      });

      if (response.ok) {
        const newPlayer = await response.json();
        setPlayers([...players, newPlayer]);
        setRequestStatus(REQ_STATUS.success);
      } else {
        console.error("Failed to add player:", response.statusText);
        setRequestStatus(REQ_STATUS.error);
      }
    } catch (error) {
      console.error(error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  const updatePlayer = async (isActive) => {
    try {
      setRequestStatus(REQ_STATUS.loading);
      const updatedPlayer = await fetch(
        `http://localhost:3001/api/players/${selectedPlayer.id}`,
        {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Basic ${window.btoa(`${username}:${password}`)}`,
          },
          body: JSON.stringify({ isActive }),
        }
      );
      setRequestStatus(REQ_STATUS.success);
    } catch (error) {
      console.error(error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  const deletePlayer = async (playerId) => {
    try {
      setRequestStatus(REQ_STATUS.loading);
      await fetch(`http://localhost:3001/api/players/${playerId}`, {
        method: "DELETE",
        headers: {
          Authorization: `Basic ${window.btoa(`${username}:${password}`)}`,
        }
      });
      const updatedPlayers = players.filter((player) => player.id !== playerId);
      setPlayers(updatedPlayers);
      setSelectedPlayer(null);
      setRequestStatus(REQ_STATUS.success);
    } catch (error) {
      console.error(error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  return (
    <div>
      <AuthUser isLoggedIn={isLoggedIn} onRegister={registerUser} onLogin={loginUser} onLogout={logoutUser}/>
      <RequestStatus>{requestStatus}</RequestStatus>
      {isLoggedIn && (
        <>
          <AddPlayer handleSubmit={addPlayer} />
          <ListPlayers players={players} getPlayer={fetchPlayerById} />
          <SelectedPlayer
            player={selectedPlayer}
            handleUpdate={updatePlayer}
            handleDelete={deletePlayer}
          />
        </>
      )}
    </div>
  );
}

export default App;

// vue/players_CRUD2/src/App.vue
<!-- 
  COPY AND PASTE THE CODE FROM THE PREVIOUS EXERCISE, BUT:
  - Beware, the template is different: AuthUser is now a child of the root div element. When copy-pasting the logic to the new template, make sure to add the AuthUser component back in. 
  - You are no longer automatically fetching the players every time the App is rendered. Instead, you should only fetch the players when the user is logged in successfully.

  What is the function of the AuthUser component in the big picture?
  - Depending on the state of the AuthUser component, the other components should be displayed or hidden (except for the RequestStatus component, which is always visible). If the user is logged in, the AddPlayer, ListPlayers, and SelectedPlayer components should be displayed. If the user is not logged in, only the AuthUser component and the RequestStatus component should be displayed.

  1. Inside the root div element, give the AuthUser the appropriate props and event listeners. It should emit the "login", "register", and "logout" events. You need to give it the "isLoggedIn" prop, which is used to determine the state of the AuthUser component. If you removed the AuthUser componenet because you overwrote the whole template with the new one, remember to add it back in.

  2. Create a method for registering a user when the AuthUser component emits the "register" event. This method should handle the logic for registering a user. After a successful registration, save the user's username and password into the App's state. 
  
  The backend uses the HTTP Basic auth, which means that the username and password as sent in base64 encoded format in the Authorization header upon every request except for the registration request. 

  The header contents should be of the following format: "Basic <base64 encoded username:password>". The username and password should be separated by a colon. The username and password should be base64 encoded. You can use the btoa() function to encode the username and password. For example, if the username is "user" and the password is "password", the header could be generated with the following code: `Basic ${window.btoa(`user:password`)}`; 

  The backend will respond with 401 if the Authorization header is missing, and with a status of 403 if the credentials are invalid. 

  After a succesful registration, the app should attempt to fetch players from the database. If it fails to fetch the players, then the user should stay logged out. If it succeeds, the user should be logged in and the app state should be updated accordingly and the players list should be displayed. Notice that separate login is not required after a successful registration, because the user is already logged in.
  
  3. Create a method for logging in when the AuthUser component emits the "login" event. This method should handle the logic for logging in a user. As described earlier, the backend does not have a separate login endpoint. Instead, the app should try to fetch players from the database with the given credentials using Basic auth. If the request is successful, the user is logged in and the app state should be updated accordingly.

  4. Create a method for logging out when the AuthUser component emits the "logout" event. This method should handle the logic for logging out a user. This method should be called when the logout event is emitted from the AuthUser component. When the user logs out, the application should be reset to its initial state (ergo, remove all data that was fetched from the database)

  HINT: Remember to add the Authorization header to every request except the user registration. 

 -->

<script setup>
import { reactive, onMounted } from "vue";

import ListPlayers from "./components/ListPlayers.vue";
import RequestStatus from "./components/RequestStatus.vue";
import SelectedPlayer from "./components/SelectedPlayer.vue";
import AddPlayer from "./components/AddPlayer.vue";
import AuthUser from "./components/AuthUser.vue";

const REQ_STATUS = {
  loading: "Loading...",
  success: "Finished!",
  error: "An error has occurred!!!",
};

const state = reactive({
  players: [],
  selectedPlayer: null,
  requestStatusMessage: REQ_STATUS.loading,
  isLoggedIn: false,
  username: null,
  password: null,
});

const registerUser = async (credentials) => {
  try {
    const { username, password } = credentials;
    state.username = username;
    state.password = password;
    state.requestStatusMessage = REQ_STATUS.loading;
    const response = await fetch("http://localhost:3001/api/users", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(credentials)
    });

    if (response.ok) {
      await fetchAllPlayers();
      state.isLoggedIn = true;
      state.requestStatusMessage = REQ_STATUS.success;
    } else {
      state.requestStatusMessage = REQ_STATUS.error;
      state.username = null;
      state.password = null;
      console.error("Failed to register user:", response.statusText);
    }
  } catch (error) {
    state.requestStatusMessage = REQ_STATUS.error;
    state.username = null;
    state.password = null;
    console.error(error);
  }
};

const loginUser = async (credentials) => {
  try {
    state.requestStatusMessage = REQ_STATUS.loading;
    const { username, password } = credentials;
    state.username = username;
    state.password = password;
    await fetchAllPlayers();
    state.isLoggedIn = true;
    state.requestStatusMessage = REQ_STATUS.success;
  } catch (error) {
    state.username = null;
    state.password = null;
    state.requestStatusMessage = REQ_STATUS.error;
    console.error(error);
  }
};

const logoutUser = async () => {
  Object.assign(state, {
    players: [],
    selectedPlayer: null,
    requestStatusMessage: REQ_STATUS.loading,
    isLoggedIn: false,
    username: null,
    password: null,
  });
  state.requestStatusMessage = ""
};

const fetchAllPlayers = async () => {
  try {
    state.players = await fetchData("http://localhost:3001/api/players");
    state.requestStatusMessage = REQ_STATUS.success;
  } catch (error) {
    console.error(error);
    state.requestStatusMessage = REQ_STATUS.error;
  }
};

const fetchPlayerById = async (playerId) => {
  try {
    state.requestStatusMessage = REQ_STATUS.loading;
    state.selectedPlayer = await fetchData(
      `http://localhost:3001/api/players/${playerId}`
    );
    state.requestStatusMessage = REQ_STATUS.success;
  } catch (error) {
    console.error(error);
    state.requestStatusMessage = REQ_STATUS.error;
  }
};

const addPlayer = async (newPlayerName) => {
  try {
    state.requestStatusMessage = REQ_STATUS.loading;

    // Make a POST request to add the new player to the database
    const response = await fetch("http://localhost:3001/api/players", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Basic ${window.btoa(`${state.username}:${state.password}`)}`,
      },
      body: JSON.stringify({ name: newPlayerName }),
    });

    if (response.ok) {
      // If the request is successful, update the players array
      const newPlayer = await response.json();
      state.players.push(newPlayer);
      state.requestStatusMessage = REQ_STATUS.success;
    } else {
      // If the request is not successful, handle the error
      console.error("Failed to add player:", response.statusText);
      state.requestStatusMessage = REQ_STATUS.error;
    }
  } catch (error) {
    console.error(error);
    state.requestStatusMessage = REQ_STATUS.error;
  }
};

const updatePlayer = async (isActive) => {
  try {
    state.requestStatusMessage = REQ_STATUS.loading;
    await fetch(
      `http://localhost:3001/api/players/${state.selectedPlayer.id}`,
      {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Basic ${window.btoa(`${state.username}:${state.password}`)}`,
        },
        body: JSON.stringify({ isActive }),
      }
    );

    state.players = state.players.map((player) =>
      player.id === state.selectedPlayer.id ? { ...player, isActive } : player
    );
    state.requestStatusMessage = REQ_STATUS.success;
  } catch (error) {
    console.error(error);
    state.requestStatusMessage = REQ_STATUS.error;
  }
};

const deletePlayer = async (playerId) => {
  try {
    state.requestStatusMessage = REQ_STATUS.loading;
    await fetch(`http://localhost:3001/api/players/${playerId}`, {
      method: "DELETE",
      headers: {
        Authorization: `Basic ${window.btoa(`${state.username}:${state.password}`)}`,
      }
    });

    state.players = state.players.filter((player) => player.id !== playerId);
    state.selectedPlayer = null;
    state.requestStatusMessage = REQ_STATUS.success;
  } catch (error) {
    console.error(error);
    state.requestStatusMessage = REQ_STATUS.error;
  }
};

onMounted(() => {
  fetchAllPlayers();
});

const fetchData = async (url) => {
  const res = await fetch(url, {
    method: "GET",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json;charset=UTF-8",
      Authorization: `Basic ${window.btoa(`${state.username}:${state.password}`)}`,
    },
  });

  const data = await res.json();
  return data;
};
</script>

<template>
  <div>
    <AuthUser :is-logged-in="state.isLoggedIn" @register="registerUser" @login="loginUser" @logout="logoutUser"/>
    <RequestStatus>
      <template v-slot:status>
        {{ state.requestStatusMessage }}
      </template>
    </RequestStatus>
    <AddPlayer v-if="state.isLoggedIn" @add-player="addPlayer" />
    <ListPlayers v-if="state.isLoggedIn" :players="state.players" :get-player="fetchPlayerById" />
    <SelectedPlayer
      v-if="state.isLoggedIn"
      :player="state.selectedPlayer"
      @put-player="updatePlayer"
      @delete-player="deletePlayer"
    />
  </div>
</template>
