// react/players_CRUD/src/components/SelectedPlayer.jsx
/**
 * Copy paste your code from the SelectedPlayer.jsx file here from the previous exercise.
 *
 * Use similar logic as in the Vue CRUD exercise to call the "handleUpdate"
 * prop function when the update button is clickable and the user clicks it.
 * In the App.jsx, this should trigger the updating of the player in the backend.
 *
 * Likewise, add logic to call the "handleDelete" prop function when the user
 * clicks the delete button. In the App.jsx, this should trigger the deletion of the player in the backend.
 *
 */
import { useEffect, useState } from "react";

export const SelectedPlayer = ({ player, handleUpdate, handleDelete }) => {
  const { id, name, isActive } = player || {};

  const [activeState, setActiveState] = useState(isActive || false);

  const checkboxChange = () => setActiveState(!activeState);

  useEffect(() => {
    setActiveState(isActive || false);
  }, [player])

  return player ? (
    <div id="selected-player">
      <div id="player-id" className="player-id">
        {id}
      </div>
      <div id="player-name">{name}</div>
      <div id="player-status">
        <label htmlFor="checkbox" id="checkbox-label">
          <input type="checkbox" id="checkbox" onChange={checkboxChange} checked={activeState}/>
          <span className="checkmark"></span>
          {activeState ? "active" : "inactive"}
        </label>
      </div>
      <button
        className="btn-update"
        disabled={activeState === isActive}
        onClick={() => handleUpdate(activeState)}
      >
        Update
      </button>
      <button className="btn-delete" onClick={() => handleDelete(id)}>
        Delete
      </button>
    </div>
  ) : (
    <></>
  );
};

// vue/players_CRUD2/src/components/SelectedPlayer.vue
<!-- 
  Copy paste your code from the ListPlayer.vue file here from the previous exercise. No changes are needed if you managed to get the component to work properly in the previous exercise.
 -->
<script setup>
import { ref, reactive, watchEffect } from "vue";

const props = defineProps({
  player: {
    type: Object,
  },
});

// console.log(props.player?.name)

const emits = defineEmits(["put-player", "delete-player"]);
// const state = reactive({isPlayerActive: props.player?.isActive});
const checkboxState = ref(props.player?.isActive);

watchEffect(() => {
  // Update checkboxState when props.player changes
  checkboxState.value = props.player?.isActive;
});

const toggle = () => {};

const updatePlayerHandler = () => {
  emits("put-player", checkboxState.value);
};

const deletePlayerHandler = () => {
  emits("delete-player", props.player?.id);
};
</script>

<template>
  <div v-if="player" id="selected-player">
    <div id="player-id" class="player-id">{{ player.id }}</div>
    <div id="player-name">{{ player.name }}</div>
    <div id="player-status">
      <label for="checkbox" id="checkbox-label">
        <input
          type="checkbox"
          id="checkbox"
          @change="toggle"
          v-model="checkboxState"
        />
        <span class="checkmark"></span>
        {{ checkboxState ? "active" : "inactive" }}
      </label>
    </div>
    <button
      class="btn-update"
      :disabled="checkboxState === player.isActive"
      @click="updatePlayerHandler"
    >
      Update
    </button>
    <button class="btn-delete" @click="deletePlayerHandler">Delete</button>
  </div>
</template>
